# Generated by Django 4.1.3 on 2022-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
    ]
