# Generated by Django 4.1.3 on 2022-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0003_user_personal_data_user_second_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошел активацию?'),
        ),
    ]
