# Generated by Django 4.1.3 on 2022-11-16 18:42

import django.core.validators
from django.db import migrations, models
import webportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0007_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), webportal.models.validate_image]),
        ),
    ]
